/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",  // Yeh already hai – perfect
  ],
  safelist: [  // Yeh add karo – important classes force generate kar dega
    'min-h-screen',
    'pb-40',
    'text-white',
    'bg-black',
    'antialiased',
    'font-sans',
    'px-5',
    'max-w-lg',
    'mx-auto',
    'min-h-[calc(100vh-180px)]',
    'glass-panel',
    'animate-slide',
    'text-cyan-400',
    'bg-cyan-500',
    'rounded-[56px]',
    'rounded-[64px]',
    'rounded-[48px]',
    'border-t-8',
    'shadow-2xl',
    'font-black',
    'tracking-widest',
    'uppercase',
    'italic',
    'hide-scrollbar',
    'backdrop-blur-3xl',
    'fixed',
    'bottom-6',
    'left-4',
    'right-4',
    'z-50',
    'p-4',
    'flex',
    'justify-between',
    'items-center',
    'border',
    'border-white/10',
    'bg-[#050505]/80',
    'border-t-2',
    'border-white/5',
  ],
  theme: {
    extend: {
      colors: {
        'accent-cyan': '#00d2ff',
        'accent-blue': '#3a7bd5',
      },
      borderRadius: {
        '56': '56px',
        '64': '64px',
        '48': '48px',
        '28': '28px',
        '40': '40px',
      },
      boxShadow: {
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      },
    },
  },
  plugins: [],
}
